# Generated by Django 2.0.4 on 2020-12-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onePgFolio', '0005_auto_20180507_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_feedback',
            name='remarks',
            field=models.TextField(max_length=400),
        ),
    ]
